// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/kikoeru_api.dart';
import 'api/proxy.dart';
import 'api/simple.dart';
import 'api/textcodec.dart';
import 'api/textconv.dart';
import 'api/translate.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -403328142;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'kikoeta_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiKikoeruApiApiCheckLrc({
    required String base,
    required String rj,
  });

  String crateApiTextconvApiConvertText({
    required String text,
    required String mode,
  });

  Future<String> crateApiKikoeruApiApiCreateFavoriteReview({
    required String base,
    required String userName,
    required BigInt workId,
  });

  DecodedText crateApiTextcodecApiDecodeText({
    required List<int> bytes,
    required String encoding,
  });

  Future<String> crateApiKikoeruApiApiDeleteFavoriteReview({
    required String base,
    required BigInt workId,
  });

  Future<Uint8List> crateApiKikoeruApiApiGetBytes({required String url});

  Future<String> crateApiKikoeruApiApiGetCustomWorks({
    required String base,
    required int page,
    required String order,
    required String sort,
    int? nsfw,
    String? lyric,
    String? seed,
  });

  Future<String> crateApiKikoeruApiApiGetMyReviews({
    required String base,
    required int page,
    required int perPage,
  });

  Future<String> crateApiKikoeruApiApiGetPlaylistWorks({
    required String base,
    required String id,
    required int page,
    required int perPage,
  });

  Future<String> crateApiKikoeruApiApiGetPlaylists({required String base});

  Future<String> crateApiKikoeruApiApiGetTracks({
    required String base,
    required String rj,
  });

  Future<String> crateApiKikoeruApiApiGetWork({
    required String base,
    required String rj,
  });

  Future<String> crateApiKikoeruApiApiGetWorks({
    required String base,
    required int page,
    required int perPage,
    required String order,
    required String sort,
    bool? subtitle,
    String? seed,
  });

  Future<String> crateApiKikoeruApiApiHealth({required String base});

  Future<String> crateApiKikoeruApiApiLogin({
    required String base,
    required String name,
    required String password,
  });

  Future<String> crateApiKikoeruApiApiPlaylistAddWorks({
    required String base,
    required String playlistId,
    required List<String> workIds,
  });

  Future<String> crateApiKikoeruApiApiPlaylistRemoveWorks({
    required String base,
    required String playlistId,
    required List<String> workIds,
  });

  Future<String> crateApiKikoeruApiApiSearch({
    required String base,
    required String query,
    required int page,
    required int perPage,
    required String order,
    required String sort,
    bool? subtitle,
    String? seed,
  });

  Future<String> crateApiKikoeruApiApiSearchCustom({
    required String base,
    required String keyword,
    required int page,
    required String order,
    required String sort,
    int? nsfw,
    String? seed,
  });

  String crateApiProxyApiStreamProxyUrl({required String url});

  Future<String> crateApiTranslateApiTranslateDeepl({
    required String text,
    required String src,
    required String dst,
    required String apiKey,
  });

  Future<String> crateApiTranslateApiTranslateGoogle({
    required String text,
    required String src,
    required String dst,
  });

  Future<String> crateApiTranslateApiTranslateMicrosoft({
    required String text,
    required String src,
    required String dst,
  });

  Future<String> crateApiTranslateApiTranslateOpenai({
    required String baseUrl,
    required String model,
    required String apiKey,
    required String text,
    required double temperature,
  });

  Future<String> crateApiTranslateApiTranslateTest({
    required String baseUrl,
    required String model,
    required String apiKey,
  });

  void crateApiSimpleClearAllSettings();

  String? crateApiSimpleGetSetting({required String key});

  String? crateApiSimpleGetToken({required String base});

  String crateApiSimpleGreet({required String name});

  Future<String?> crateApiSimpleHttpProxyConfig();

  Future<void> crateApiSimpleInitApp();

  void crateApiSimpleOpenSettings({required String path});

  Future<int?> crateApiProxyProxyPort();

  String crateApiSimpleRustPlatform();

  Future<void> crateApiSimpleSaveTokenForBase({
    required String base,
    required String token,
  });

  void crateApiSimpleSetSetting({required String key, required String value});

  Future<String?> crateApiSimpleTokenForBase({required String base});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiKikoeruApiApiCheckLrc({
    required String base,
    required String rj,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(rj, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiCheckLrcConstMeta,
        argValues: [base, rj],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiCheckLrcConstMeta =>
      const TaskConstMeta(debugName: "api_check_lrc", argNames: ["base", "rj"]);

  @override
  String crateApiTextconvApiConvertText({
    required String text,
    required String mode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTextconvApiConvertTextConstMeta,
        argValues: [text, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTextconvApiConvertTextConstMeta =>
      const TaskConstMeta(
        debugName: "api_convert_text",
        argNames: ["text", "mode"],
      );

  @override
  Future<String> crateApiKikoeruApiApiCreateFavoriteReview({
    required String base,
    required String userName,
    required BigInt workId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(userName, serializer);
          sse_encode_u_64(workId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiCreateFavoriteReviewConstMeta,
        argValues: [base, userName, workId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiCreateFavoriteReviewConstMeta =>
      const TaskConstMeta(
        debugName: "api_create_favorite_review",
        argNames: ["base", "userName", "workId"],
      );

  @override
  DecodedText crateApiTextcodecApiDecodeText({
    required List<int> bytes,
    required String encoding,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(encoding, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_decoded_text,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTextcodecApiDecodeTextConstMeta,
        argValues: [bytes, encoding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTextcodecApiDecodeTextConstMeta =>
      const TaskConstMeta(
        debugName: "api_decode_text",
        argNames: ["bytes", "encoding"],
      );

  @override
  Future<String> crateApiKikoeruApiApiDeleteFavoriteReview({
    required String base,
    required BigInt workId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_u_64(workId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiDeleteFavoriteReviewConstMeta,
        argValues: [base, workId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiDeleteFavoriteReviewConstMeta =>
      const TaskConstMeta(
        debugName: "api_delete_favorite_review",
        argNames: ["base", "workId"],
      );

  @override
  Future<Uint8List> crateApiKikoeruApiApiGetBytes({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiGetBytesConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiGetBytesConstMeta =>
      const TaskConstMeta(debugName: "api_get_bytes", argNames: ["url"]);

  @override
  Future<String> crateApiKikoeruApiApiGetCustomWorks({
    required String base,
    required int page,
    required String order,
    required String sort,
    int? nsfw,
    String? lyric,
    String? seed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_u_32(page, serializer);
          sse_encode_String(order, serializer);
          sse_encode_String(sort, serializer);
          sse_encode_opt_box_autoadd_i_32(nsfw, serializer);
          sse_encode_opt_String(lyric, serializer);
          sse_encode_opt_String(seed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiGetCustomWorksConstMeta,
        argValues: [base, page, order, sort, nsfw, lyric, seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiGetCustomWorksConstMeta =>
      const TaskConstMeta(
        debugName: "api_get_custom_works",
        argNames: ["base", "page", "order", "sort", "nsfw", "lyric", "seed"],
      );

  @override
  Future<String> crateApiKikoeruApiApiGetMyReviews({
    required String base,
    required int page,
    required int perPage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_u_32(page, serializer);
          sse_encode_u_32(perPage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiGetMyReviewsConstMeta,
        argValues: [base, page, perPage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiGetMyReviewsConstMeta =>
      const TaskConstMeta(
        debugName: "api_get_my_reviews",
        argNames: ["base", "page", "perPage"],
      );

  @override
  Future<String> crateApiKikoeruApiApiGetPlaylistWorks({
    required String base,
    required String id,
    required int page,
    required int perPage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(id, serializer);
          sse_encode_u_32(page, serializer);
          sse_encode_u_32(perPage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiGetPlaylistWorksConstMeta,
        argValues: [base, id, page, perPage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiGetPlaylistWorksConstMeta =>
      const TaskConstMeta(
        debugName: "api_get_playlist_works",
        argNames: ["base", "id", "page", "perPage"],
      );

  @override
  Future<String> crateApiKikoeruApiApiGetPlaylists({required String base}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiGetPlaylistsConstMeta,
        argValues: [base],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiGetPlaylistsConstMeta =>
      const TaskConstMeta(debugName: "api_get_playlists", argNames: ["base"]);

  @override
  Future<String> crateApiKikoeruApiApiGetTracks({
    required String base,
    required String rj,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(rj, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiGetTracksConstMeta,
        argValues: [base, rj],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiGetTracksConstMeta =>
      const TaskConstMeta(
        debugName: "api_get_tracks",
        argNames: ["base", "rj"],
      );

  @override
  Future<String> crateApiKikoeruApiApiGetWork({
    required String base,
    required String rj,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(rj, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiGetWorkConstMeta,
        argValues: [base, rj],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiGetWorkConstMeta =>
      const TaskConstMeta(debugName: "api_get_work", argNames: ["base", "rj"]);

  @override
  Future<String> crateApiKikoeruApiApiGetWorks({
    required String base,
    required int page,
    required int perPage,
    required String order,
    required String sort,
    bool? subtitle,
    String? seed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_u_32(page, serializer);
          sse_encode_u_32(perPage, serializer);
          sse_encode_String(order, serializer);
          sse_encode_String(sort, serializer);
          sse_encode_opt_box_autoadd_bool(subtitle, serializer);
          sse_encode_opt_String(seed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiGetWorksConstMeta,
        argValues: [base, page, perPage, order, sort, subtitle, seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiGetWorksConstMeta =>
      const TaskConstMeta(
        debugName: "api_get_works",
        argNames: [
          "base",
          "page",
          "perPage",
          "order",
          "sort",
          "subtitle",
          "seed",
        ],
      );

  @override
  Future<String> crateApiKikoeruApiApiHealth({required String base}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiHealthConstMeta,
        argValues: [base],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiHealthConstMeta =>
      const TaskConstMeta(debugName: "api_health", argNames: ["base"]);

  @override
  Future<String> crateApiKikoeruApiApiLogin({
    required String base,
    required String name,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiLoginConstMeta,
        argValues: [base, name, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiLoginConstMeta => const TaskConstMeta(
    debugName: "api_login",
    argNames: ["base", "name", "password"],
  );

  @override
  Future<String> crateApiKikoeruApiApiPlaylistAddWorks({
    required String base,
    required String playlistId,
    required List<String> workIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(playlistId, serializer);
          sse_encode_list_String(workIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiPlaylistAddWorksConstMeta,
        argValues: [base, playlistId, workIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiPlaylistAddWorksConstMeta =>
      const TaskConstMeta(
        debugName: "api_playlist_add_works",
        argNames: ["base", "playlistId", "workIds"],
      );

  @override
  Future<String> crateApiKikoeruApiApiPlaylistRemoveWorks({
    required String base,
    required String playlistId,
    required List<String> workIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(playlistId, serializer);
          sse_encode_list_String(workIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiPlaylistRemoveWorksConstMeta,
        argValues: [base, playlistId, workIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiPlaylistRemoveWorksConstMeta =>
      const TaskConstMeta(
        debugName: "api_playlist_remove_works",
        argNames: ["base", "playlistId", "workIds"],
      );

  @override
  Future<String> crateApiKikoeruApiApiSearch({
    required String base,
    required String query,
    required int page,
    required int perPage,
    required String order,
    required String sort,
    bool? subtitle,
    String? seed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(query, serializer);
          sse_encode_u_32(page, serializer);
          sse_encode_u_32(perPage, serializer);
          sse_encode_String(order, serializer);
          sse_encode_String(sort, serializer);
          sse_encode_opt_box_autoadd_bool(subtitle, serializer);
          sse_encode_opt_String(seed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiSearchConstMeta,
        argValues: [base, query, page, perPage, order, sort, subtitle, seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiSearchConstMeta =>
      const TaskConstMeta(
        debugName: "api_search",
        argNames: [
          "base",
          "query",
          "page",
          "perPage",
          "order",
          "sort",
          "subtitle",
          "seed",
        ],
      );

  @override
  Future<String> crateApiKikoeruApiApiSearchCustom({
    required String base,
    required String keyword,
    required int page,
    required String order,
    required String sort,
    int? nsfw,
    String? seed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(keyword, serializer);
          sse_encode_u_32(page, serializer);
          sse_encode_String(order, serializer);
          sse_encode_String(sort, serializer);
          sse_encode_opt_box_autoadd_i_32(nsfw, serializer);
          sse_encode_opt_String(seed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiKikoeruApiApiSearchCustomConstMeta,
        argValues: [base, keyword, page, order, sort, nsfw, seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKikoeruApiApiSearchCustomConstMeta =>
      const TaskConstMeta(
        debugName: "api_search_custom",
        argNames: ["base", "keyword", "page", "order", "sort", "nsfw", "seed"],
      );

  @override
  String crateApiProxyApiStreamProxyUrl({required String url}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProxyApiStreamProxyUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProxyApiStreamProxyUrlConstMeta =>
      const TaskConstMeta(debugName: "api_stream_proxy_url", argNames: ["url"]);

  @override
  Future<String> crateApiTranslateApiTranslateDeepl({
    required String text,
    required String src,
    required String dst,
    required String apiKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(src, serializer);
          sse_encode_String(dst, serializer);
          sse_encode_String(apiKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTranslateApiTranslateDeeplConstMeta,
        argValues: [text, src, dst, apiKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranslateApiTranslateDeeplConstMeta =>
      const TaskConstMeta(
        debugName: "api_translate_deepl",
        argNames: ["text", "src", "dst", "apiKey"],
      );

  @override
  Future<String> crateApiTranslateApiTranslateGoogle({
    required String text,
    required String src,
    required String dst,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(src, serializer);
          sse_encode_String(dst, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTranslateApiTranslateGoogleConstMeta,
        argValues: [text, src, dst],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranslateApiTranslateGoogleConstMeta =>
      const TaskConstMeta(
        debugName: "api_translate_google",
        argNames: ["text", "src", "dst"],
      );

  @override
  Future<String> crateApiTranslateApiTranslateMicrosoft({
    required String text,
    required String src,
    required String dst,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(src, serializer);
          sse_encode_String(dst, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTranslateApiTranslateMicrosoftConstMeta,
        argValues: [text, src, dst],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranslateApiTranslateMicrosoftConstMeta =>
      const TaskConstMeta(
        debugName: "api_translate_microsoft",
        argNames: ["text", "src", "dst"],
      );

  @override
  Future<String> crateApiTranslateApiTranslateOpenai({
    required String baseUrl,
    required String model,
    required String apiKey,
    required String text,
    required double temperature,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(model, serializer);
          sse_encode_String(apiKey, serializer);
          sse_encode_String(text, serializer);
          sse_encode_f_64(temperature, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTranslateApiTranslateOpenaiConstMeta,
        argValues: [baseUrl, model, apiKey, text, temperature],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranslateApiTranslateOpenaiConstMeta =>
      const TaskConstMeta(
        debugName: "api_translate_openai",
        argNames: ["baseUrl", "model", "apiKey", "text", "temperature"],
      );

  @override
  Future<String> crateApiTranslateApiTranslateTest({
    required String baseUrl,
    required String model,
    required String apiKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(model, serializer);
          sse_encode_String(apiKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTranslateApiTranslateTestConstMeta,
        argValues: [baseUrl, model, apiKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTranslateApiTranslateTestConstMeta =>
      const TaskConstMeta(
        debugName: "api_translate_test",
        argNames: ["baseUrl", "model", "apiKey"],
      );

  @override
  void crateApiSimpleClearAllSettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleClearAllSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleClearAllSettingsConstMeta =>
      const TaskConstMeta(debugName: "clear_all_settings", argNames: []);

  @override
  String? crateApiSimpleGetSetting({required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetSettingConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetSettingConstMeta =>
      const TaskConstMeta(debugName: "get_setting", argNames: ["key"]);

  @override
  String? crateApiSimpleGetToken({required String base}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetTokenConstMeta,
        argValues: [base],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTokenConstMeta =>
      const TaskConstMeta(debugName: "get_token", argNames: ["base"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<String?> crateApiSimpleHttpProxyConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleHttpProxyConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleHttpProxyConfigConstMeta =>
      const TaskConstMeta(debugName: "http_proxy_config", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiSimpleOpenSettings({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleOpenSettingsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleOpenSettingsConstMeta =>
      const TaskConstMeta(debugName: "open_settings", argNames: ["path"]);

  @override
  Future<int?> crateApiProxyProxyPort() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProxyProxyPortConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProxyProxyPortConstMeta =>
      const TaskConstMeta(debugName: "proxy_port", argNames: []);

  @override
  String crateApiSimpleRustPlatform() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRustPlatformConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRustPlatformConstMeta =>
      const TaskConstMeta(debugName: "rust_platform", argNames: []);

  @override
  Future<void> crateApiSimpleSaveTokenForBase({
    required String base,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSaveTokenForBaseConstMeta,
        argValues: [base, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSaveTokenForBaseConstMeta =>
      const TaskConstMeta(
        debugName: "save_token_for_base",
        argNames: ["base", "token"],
      );

  @override
  void crateApiSimpleSetSetting({required String key, required String value}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSetSettingConstMeta,
        argValues: [key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetSettingConstMeta =>
      const TaskConstMeta(debugName: "set_setting", argNames: ["key", "value"]);

  @override
  Future<String?> crateApiSimpleTokenForBase({required String base}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(base, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTokenForBaseConstMeta,
        argValues: [base],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTokenForBaseConstMeta =>
      const TaskConstMeta(debugName: "token_for_base", argNames: ["base"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  DecodedText dco_decode_decoded_text(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DecodedText(
      encoding: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  DecodedText sse_decode_decoded_text(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_encoding = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    return DecodedText(encoding: var_encoding, text: var_text);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_decoded_text(DecodedText self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.encoding, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
