// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_custom_params`, `append_filter_params`, `auth_header`, `base_of`, `http_client`, `http_delete`, `http_get`, `http_post_json`, `http_put_json`, `origin_of`, `urlencoding`

/// 作品列表：GET /api/works?page=&per_page=&order=&sort=&subtitle=&seed=
Future<String> apiGetWorks({
  required String base,
  required int page,
  required int perPage,
  required String order,
  required String sort,
  bool? subtitle,
  String? seed,
}) => RustLib.instance.api.crateApiKikoeruApiApiGetWorks(
  base: base,
  page: page,
  perPage: perPage,
  order: order,
  sort: sort,
  subtitle: subtitle,
  seed: seed,
);

/// 随心听：GET /api/works?order=betterRandom
Future<String> apiGetRandomWork({required String base}) =>
    RustLib.instance.api.crateApiKikoeruApiApiGetRandomWork(base: base);

/// asmr.one 热门作品：POST /api/recommender/popular
Future<String> apiGetRecommenderPopular({
  required String base,
  required String keyword,
  required int page,
  required bool subtitle,
}) => RustLib.instance.api.crateApiKikoeruApiApiGetRecommenderPopular(
  base: base,
  keyword: keyword,
  page: page,
  subtitle: subtitle,
);

/// asmr.one 推荐作品：POST /api/recommender/recommend-for-user
Future<String> apiGetRecommenderRecommend({
  required String base,
  required String recommenderUuid,
  required String keyword,
  required int page,
  required bool subtitle,
}) => RustLib.instance.api.crateApiKikoeruApiApiGetRecommenderRecommend(
  base: base,
  recommenderUuid: recommenderUuid,
  keyword: keyword,
  page: page,
  subtitle: subtitle,
);

/// 搜索：GET /api/search/{query}?page=&per_page=&order=&sort=&subtitle=
Future<String> apiSearch({
  required String base,
  required String query,
  required int page,
  required int perPage,
  required String order,
  required String sort,
  bool? subtitle,
  String? seed,
}) => RustLib.instance.api.crateApiKikoeruApiApiSearch(
  base: base,
  query: query,
  page: page,
  perPage: perPage,
  order: order,
  sort: sort,
  subtitle: subtitle,
  seed: seed,
);

/// 自建站（kikoeru-express 兼容）作品列表：
/// GET /api/works?page=&order=&sort=&nsfw=&lyric=&seed=
Future<String> apiGetCustomWorks({
  required String base,
  required int page,
  required String order,
  required String sort,
  int? nsfw,
  String? lyric,
  String? seed,
}) => RustLib.instance.api.crateApiKikoeruApiApiGetCustomWorks(
  base: base,
  page: page,
  order: order,
  sort: sort,
  nsfw: nsfw,
  lyric: lyric,
  seed: seed,
);

/// 自建站（kikoeru-express 兼容）搜索：
/// GET /api/search?keyword=&page=&order=&sort=&nsfw=&seed=
Future<String> apiSearchCustom({
  required String base,
  required String keyword,
  required int page,
  required String order,
  required String sort,
  int? nsfw,
  String? seed,
}) => RustLib.instance.api.crateApiKikoeruApiApiSearchCustom(
  base: base,
  keyword: keyword,
  page: page,
  order: order,
  sort: sort,
  nsfw: nsfw,
  seed: seed,
);

/// 作品详情：GET /api/work/{rj}
Future<String> apiGetWork({required String base, required String rj}) =>
    RustLib.instance.api.crateApiKikoeruApiApiGetWork(base: base, rj: rj);

/// 曲目列表：GET /api/tracks/{rj}
Future<String> apiGetTracks({required String base, required String rj}) =>
    RustLib.instance.api.crateApiKikoeruApiApiGetTracks(base: base, rj: rj);

/// 下载任意 URL 的原始字节（用于封面等图片，绕过 dart:io 的 TLS 问题）
Future<Uint8List> apiGetBytes({required String url}) =>
    RustLib.instance.api.crateApiKikoeruApiApiGetBytes(url: url);

/// 连接检测：GET /api/health，返回耗时
Future<String> apiHealth({required String base}) =>
    RustLib.instance.api.crateApiKikoeruApiApiHealth(base: base);

/// 使用用户自己的账号登录服务器（one 站 / 自建站），成功返回并保存 token
Future<String> apiLogin({
  required String base,
  required String name,
  required String password,
}) => RustLib.instance.api.crateApiKikoeruApiApiLogin(
  base: base,
  name: name,
  password: password,
);

/// 获取作品歌词：GET /api/media/check-lrc/{rj}（需登录）
Future<String> apiCheckLrc({required String base, required String rj}) =>
    RustLib.instance.api.crateApiKikoeruApiApiCheckLrc(base: base, rj: rj);

/// 歌单列表：GET /api/playlist/get-playlists（需登录）
Future<String> apiGetPlaylists({required String base}) =>
    RustLib.instance.api.crateApiKikoeruApiApiGetPlaylists(base: base);

/// 歌单作品：GET /api/playlist/get-playlist-works?id=...（需登录）
Future<String> apiGetPlaylistWorks({
  required String base,
  required String id,
  required int page,
  required int perPage,
}) => RustLib.instance.api.crateApiKikoeruApiApiGetPlaylistWorks(
  base: base,
  id: id,
  page: page,
  perPage: perPage,
);

/// 添加作品到歌单：POST /api/playlist/add-works-to-playlist
Future<String> apiPlaylistAddWorks({
  required String base,
  required String playlistId,
  required List<String> workIds,
}) => RustLib.instance.api.crateApiKikoeruApiApiPlaylistAddWorks(
  base: base,
  playlistId: playlistId,
  workIds: workIds,
);

/// 从歌单移除作品：POST /api/playlist/remove-works-from-playlist
Future<String> apiPlaylistRemoveWorks({
  required String base,
  required String playlistId,
  required List<String> workIds,
}) => RustLib.instance.api.crateApiKikoeruApiApiPlaylistRemoveWorks(
  base: base,
  playlistId: playlistId,
  workIds: workIds,
);

/// 收藏作品：创建无评分的 listening 评价。
Future<String> apiCreateFavoriteReview({
  required String base,
  required String userName,
  required BigInt workId,
}) => RustLib.instance.api.crateApiKikoeruApiApiCreateFavoriteReview(
  base: base,
  userName: userName,
  workId: workId,
);

/// 取消收藏：删除该作品的评价。
Future<String> apiDeleteFavoriteReview({
  required String base,
  required BigInt workId,
}) => RustLib.instance.api.crateApiKikoeruApiApiDeleteFavoriteReview(
  base: base,
  workId: workId,
);

/// 我的评价/收藏列表：GET /api/review（需登录）
Future<String> apiGetMyReviews({
  required String base,
  required int page,
  required int perPage,
}) => RustLib.instance.api.crateApiKikoeruApiApiGetMyReviews(
  base: base,
  page: page,
  perPage: perPage,
);
