// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_proxy`, `handle_request`, `hex_val`, `percent_decode`, `percent_encode`, `proxy_client`, `query_param`

/// 把一个远程媒体 URL 转成本地代理 URL（首次调用会启动本地代理）。
String apiStreamProxyUrl({required String url}) =>
    RustLib.instance.api.crateApiProxyApiStreamProxyUrl(url: url);

/// 供其它模块查询当前代理端口（测试/调试用）
Future<int?> proxyPort() => RustLib.instance.api.crateApiProxyProxyPort();
