// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// 打开（或创建）设置数据库，并建好 settings 表。
void openSettings({required String path}) =>
    RustLib.instance.api.crateApiSimpleOpenSettings(path: path);

String? getSetting({required String key}) =>
    RustLib.instance.api.crateApiSimpleGetSetting(key: key);

void setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiSimpleSetSetting(key: key, value: value);

/// 清空全部设置与 token（「完全重置」用）
void clearAllSettings() =>
    RustLib.instance.api.crateApiSimpleClearAllSettings();

String rustPlatform() => RustLib.instance.api.crateApiSimpleRustPlatform();

/// 按服务器保存登录 token（本地 SQLite）
Future<void> saveTokenForBase({required String base, required String token}) =>
    RustLib.instance.api.crateApiSimpleSaveTokenForBase(
      base: base,
      token: token,
    );

/// 读取某服务器的 token
Future<String?> tokenForBase({required String base}) =>
    RustLib.instance.api.crateApiSimpleTokenForBase(base: base);

/// 供 Dart 获取某服务器的 token（用于播放器流请求头）
String? getToken({required String base}) =>
    RustLib.instance.api.crateApiSimpleGetToken(base: base);

/// 读取 HTTP 代理配置（仅支持 HTTP 代理；未启用/非法时返回 None）
Future<String?> httpProxyConfig() =>
    RustLib.instance.api.crateApiSimpleHttpProxyConfig();
