// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `auto_decode`, `decode_utf16`, `decode_with`, `has_iso2022jp_marker`, `strict_decode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// 解码文本。`encoding` 为空时自动检测；否则按指定编码解码。
DecodedText apiDecodeText({
  required List<int> bytes,
  required String encoding,
}) => RustLib.instance.api.crateApiTextcodecApiDecodeText(
  bytes: bytes,
  encoding: encoding,
);

class DecodedText {
  final String encoding;
  final String text;

  const DecodedText({required this.encoding, required this.text});

  @override
  int get hashCode => encoding.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedText &&
          runtimeType == other.runtimeType &&
          encoding == other.encoding &&
          text == other.text;
}
