// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `deepl_lang`, `fetch_edge_token`, `http_client`, `microsoft_lang`, `normalize_base`, `parse_completion`, `parse_google`, `preview`

/// 调用 OpenAI 兼容接口翻译文本。text 为多行拼接内容，返回翻译结果。
Future<String> apiTranslateOpenai({
  required String baseUrl,
  required String model,
  required String apiKey,
  required String text,
  required double temperature,
}) => RustLib.instance.api.crateApiTranslateApiTranslateOpenai(
  baseUrl: baseUrl,
  model: model,
  apiKey: apiKey,
  text: text,
  temperature: temperature,
);

/// Google 免费翻译接口（translate.googleapis.com gtx，无需 Key）。
/// 作用范围与 OpenAI 一致：多行标题拼接翻译，保持行数。
Future<String> apiTranslateGoogle({
  required String text,
  required String src,
  required String dst,
}) => RustLib.instance.api.crateApiTranslateApiTranslateGoogle(
  text: text,
  src: src,
  dst: dst,
);

/// DeepL 免费版接口（api-free.deepl.com/v2/translate，需免费注册的 auth_key）。
Future<String> apiTranslateDeepl({
  required String text,
  required String src,
  required String dst,
  required String apiKey,
}) => RustLib.instance.api.crateApiTranslateApiTranslateDeepl(
  text: text,
  src: src,
  dst: dst,
  apiKey: apiKey,
);

/// Microsoft 免费翻译（Edge 浏览器同款接口，无需 Key）：
/// 先从 edge.microsoft.com 取匿名 token，再调 api-edge 翻译。
Future<String> apiTranslateMicrosoft({
  required String text,
  required String src,
  required String dst,
}) => RustLib.instance.api.crateApiTranslateApiTranslateMicrosoft(
  text: text,
  src: src,
  dst: dst,
);

/// 测试连接：GET {base}/models，校验 key 是否有效。
Future<String> apiTranslateTest({
  required String baseUrl,
  required String model,
  required String apiKey,
}) => RustLib.instance.api.crateApiTranslateApiTranslateTest(
  baseUrl: baseUrl,
  model: model,
  apiKey: apiKey,
);
